{
 "title": "Warehouse Manager",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(WarehouseValue,k8s_pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Warehouse Value",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "WarehouseValue", "legendFormat": "{{deployment}}" }
   ]
  },
  {
   "title": "Warehouse Value",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    { "expr": "WarehouseValue", "legendFormat": "{{deployment}}" }
   ]
  },
  {
   "title": "Current Goods Envelope",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rate(GoodsEnvelope{}[5m])", "legendFormat": "{{envelope_type}}" }
   ]
  },
  {
   "title": "Current Goods Envelope - IN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(GoodsEnvelope_total{envelope_type=~\"in|out\"})",
     "legendFormat": "{{envelope_type}}"
    }
   ]
  },
  { "title": "Runtime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "GC Collections Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_collections_count_total{k8s_pod_name=\"$instance\"}",
     "legendFormat": "{{generation}}"
    }
   ]
  },
  {
   "title": "Committed Memory Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_runtime_dotnet_gc_committed_memory_size_bytes{k8s_pod_name=\"$instance\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}