{
 "title": "K8s Cluster",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ready Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(k8s_node_condition_ready)", "legendFormat": "{{k8s_node_name}}" }
   ]
  },
  {
   "title": "Running pods in Cluster",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(k8s_pod_phase==2)", "legendFormat": "{{k8s_node_name}}" }
   ]
  },
  {
   "title": "Requested Memory",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_container_memory_request)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requested CPU",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "CPU" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(k8s_container_cpu_request)", "legendFormat": "__auto" }
   ]
  },
  { "title": "Detailed Cluster Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Deployments per Namespace",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_deployment_available) by (k8s_namespace_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "K8s Jobs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "sum(k8s_job_failed_pods)", "legendFormat": "Failed Jobs" },
    { "expr": "sum(k8s_job_successful_pods)", "legendFormat": "Successfull Jobs" }
   ]
  },
  { "title": "Hardware Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Total Memory usage by Pods",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(k8s_pod_memory_usage)", "legendFormat": "{{k8s_pod_name}}" }
   ]
  },
  {
   "title": "Current Network OUT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(k8s_node_network_io{direction=\"transmit\", k8s_node_name!=\"\"}[1m])",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Current Network IN",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(k8s_node_network_io{direction=\"receive\", k8s_node_name!=\"\"}[1m])",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "CPU usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "k8s_pod_cpu_utilization", "legendFormat": "{{k8s_pod_name}}" }
   ]
  },
  {
   "title": "Memory usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "k8s_pod_memory_usage", "legendFormat": "{{k8s_pod_name}}" }
   ]
  },
  {
   "title": "Network IN by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "k8s_pod_network_io{direction=\"receive\"}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Network OUT by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "k8s_pod_network_io{direction=\"transmit\"}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  }
 ]
}